//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID { get; set; }
        public string HrName { get; set; }
        public string EmployeeName { get; set; }
        public int EmployeeId { get; set; }
        public int DepartmentId { get; set; }
        public System.DateTime from { get; set; }
        public System.DateTime To { get; set; }
        public string Type { get; set; }
        public Nullable<int> NumberOfDay { get; set; }
        public Nullable<int> NumberOfHours { get; set; }
        public string status { get; set; }
        public string Description { get; set; }
        public string Response { get; set; }
    }
}
